# Generated by Django 4.2.8 on 2026-01-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_finalquestion_temp_delete_main_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='finalquestion',
            name='question_text',
            field=models.JSONField(default=list),
        ),
    ]
