# Generated by Django 4.2.8 on 2026-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_finalquestion_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalquestion',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='test_id',
        ),
        migrations.AddField(
            model_name='temp',
            name='current_complexity',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='temp',
            name='current_file',
            field=models.FileField(blank=True, null=True, upload_to='temp_pdfs/'),
        ),
        migrations.AddField(
            model_name='temp',
            name='current_topic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='current_type',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='temp',
            name='target_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='finalquestion',
            name='answers_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
